# Generated by Django 4.0 on 2022-01-04 18:29

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer.', max_length=100, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone nomber')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='phone nomber')),
                ('company_name', models.CharField(max_length=25, verbose_name='last name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sales_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.BooleanField(default=True)),
                ('attendees', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('event_date', models.DateField()),
                ('notes', models.TextField(max_length=1000)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
                ('support_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_contact', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.BooleanField(default=True)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('payment_due', models.DateField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
                ('sales_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_contact', to='accounts.customuser')),
            ],
        ),
    ]
